spring.application.name=sb-ecommerce

#for database configuration
#spring.h2.console.enabled=****
#spring.datasource.url=*********

#spring.datasource.url=************
#spring.datasource.username=****
#spring.datasource.password=*********

#pring.jpa.hibernate.ddl-auto=********
#spring.jpa.show-sql=*******
#spring.jpa.properties.hibernate.dialect=*************


spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=Retrospace$##@1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

project.image=images/

#for debugging purpose

#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.hibernate.ddl-auto=update

spring.app.jwtSecret=mySecretKeyghgkhgkuffhmjgliugvjvjhfygsdfgergsrgaewrwregre
spring.app.jwtExpirationMs=3000000
spring.ecom.app.jwtCookieName=springBootEcom


#logging.level.org.springframework=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.com.ecommerce.sbEcommerce=DEBUG
server.port=8080
image.base.url=http://localhost:8080/images/

#STRIPE KEY
stripe.secret.key=sk_test_51R1qbwCxsaXZVgeHZkN0SvwvSGOYh3FGX3JHuvOSHKIhLDdbdIhPBwIxGm8laNuEqlhmuAvu5sfnfA8w2paF636S00XaheQiyD





